"
I am an example class
"
Class {
	#name : 'RowanSample9V3Class2',
	#superclass : 'Object',
	#instVars : [
		'ivar1'
	],
	#category : 'RowanSample9V3-Core'
}

Class {
	#name : 'RowanSample9V3Class1',
	#superclass : 'Object',
	#instVars : [
		'ivar1'
	],
	#category : 'RowanSample9V3-Core'
}

{ #category : 'accessing' }
RowanSample9V3Class1 >> foo [ ^1
]
{ #category : 'accessing' }
RowanSample9V3Class1 >> foo [ ^2
]
